Repository iotaledger/entangled, pull requests merged in 2019-02, with the labels that each got.

#774 mam2: remove polymorphic sponge transformation
  mam/v2/ntru/tests/test_ntru.c
  mam/v2/sponge/sponge.c
  mam/v2/sponge/sponge.h
  mam/v2/test_utils/test_utils.c
Labels: A-mam2

#776 mam2: remove PRNG's sponge field
  mam/v2/mam/tests/test_mam.c
  mam/v2/mss/tests/test_mss.c
  mam/v2/ntru/tests/test_ntru.c
  mam/v2/prng/prng.c
  mam/v2/prng/prng.h
  mam/v2/prng/prng_types.h
  mam/v2/prng/tests/test_prng.c
  mam/v2/test_utils/test_utils.c
  mam/v2/test_utils/test_utils.h
  mam/v2/wots/tests/test_wots.c
Labels: A-mam2

#775 mam2: remove MSS's WOTS field
  mam/v2/mam/mam.c
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
  mam/v2/mss/tests/test_mss.c
  mam/v2/wots/wots.c
  mam/v2/wots/wots.h
Labels: A-mam2

#777 mam2: remove test structs
  mam/v2/mam/tests/test_mam.c
  mam/v2/mss/mss.c
  mam/v2/mss/tests/test_mss.c
  mam/v2/ntru/ntru.c
  mam/v2/ntru/ntru.h
  mam/v2/ntru/ntru_types.c
  mam/v2/ntru/tests/test_ntru.c
  mam/v2/prng/tests/test_prng.c
  mam/v2/sponge/spongos.c
  mam/v2/sponge/spongos.h
  mam/v2/sponge/tests/test_sponge.c
  mam/v2/sponge/tests/test_spongos.c
  mam/v2/test_utils/test_utils.c
  mam/v2/test_utils/test_utils.h
  mam/v2/wots/tests/test_wots.c
  mam/v2/wots/wots.c
  mam/v2/wots/wots.h
Labels: A-mam2

#758 mam2: endpoints serialization
  mam/v2/mam/BUILD
  mam/v2/mam/endpoint.c
  mam/v2/mam/endpoint.h
  mam/v2/mam/tests/BUILD
  mam/v2/mam/tests/test_endpoint.c
  mam/v2/mam/tests/test_mam.c
  mam/v2/mam/tests/test_mam_types.c
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
Labels: A-mam2, S-ready-for-review

#767 mam2: channels serialization
  mam/v2/mam/BUILD
  mam/v2/mam/channel.c
  mam/v2/mam/channel.h
  mam/v2/mam/endpoint.c
  mam/v2/mam/endpoint.h
  mam/v2/mam/tests/BUILD
  mam/v2/mam/tests/test_channel.c
  mam/v2/mam/tests/test_endpoint.c
  mam/v2/mam/tests/test_mam.c
  mam/v2/mss/mss.h
  utils/containers/set.c.tpl
Labels: A-mam2

#782 mam2/ntru: remove dynamic allocation of polynomials
  mam/v2/ntru/BUILD
  mam/v2/ntru/ntru.c
  mam/v2/ntru/ntru.h
  mam/v2/ntru/ntru_types.h
  mam/v2/ntru/tests/test_ntru.c
Labels: A-mam2, C-enhancement

#780 common/trinary: fix test case names
  common/trinary/tests/test_trit_tryte.c
Labels: A-common, C-cleanup

#768 mam2: state struct
  mam/v2/prng/prng.c
  mam/v2/prng/prng.h
  mam/v2/state/BUILD
  mam/v2/state/state.c
  mam/v2/state/state.h
Labels: A-mam2

#785 mam2: remove debug code
  mam/v2/defs.h
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
  mam/v2/mss/tests/test_mss.c
  mam/v2/trits/trits.h
Labels: A-mam2, C-cleanup

#804 utils: move sockets to handles
  cclient/http/BUILD
  cclient/http/http.c
  network/BUILD
  utils/handles/BUILD
  utils/handles/socket.c
  utils/handles/socket.h
Labels: A-infra, C-enhancement

#808 infra: Update Android SDK and NDK to API level 27
  WORKSPACE
Labels: A-mobile, C-enhancement

#797 mam2: psk, ntru_pk and ntru_sk api
  mam/v2/mam/BUILD
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
  mam/v2/mam/mam_types.c
  mam/v2/mam/mam_types.h
  mam/v2/mam/tests/BUILD
  mam/v2/mam/tests/test_mam.c
  mam/v2/mam/tests/test_mam_types.c
  mam/v2/state/BUILD
  mam/v2/state/state.c
  mam/v2/state/state.h
Labels: A-mam2, S-ready-for-review

#784 mam2: remove MSS spongos member
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
Labels: A-mam2, C-cleanup, S-ready-for-review

#798 mam2: mss clean and test serialization
  mam/v2/mam/channel.c
  mam/v2/mam/endpoint.c
  mam/v2/mam/tests/test_channel.c
  mam/v2/mam/tests/test_endpoint.c
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
  mam/v2/mss/tests/test_mss.c
Labels: A-mam2, C-cleanup, S-ready-for-review

#787 mam2: fix mam test type warning
  mam/v2/mam/tests/test_mam.c
  mam/v2/ntru/tests/test_ntru_types.c
Labels: A-mam2, C-bug, S-ready-for-review

#801 mam2: merge state and bundle into api
  mam/v2/api/BUILD
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/bundle/BUILD
  mam/v2/bundle/bundle.c
  mam/v2/bundle/bundle.h
  mam/v2/state/state.c
  mam/v2/state/state.h
Labels: A-mam2, C-cleanup, S-ready-for-review

#802 mam2: replicate spec changes
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
  mam/v2/mam/tests/test_mam.c
  mam/v2/mss/mss.c
  mam/v2/mss/mss.h
  mam/v2/ntru/ntru.c
  mam/v2/trits/trits.c
Labels: A-mam2, C-enhancement, S-ready-for-review

#806 mam2/sponge: remove stack from struct
  mam/v2/sponge/sponge.c
  mam/v2/sponge/sponge.h
  mam/v2/sponge/tests/test_spongos.c
Labels: A-mam2, C-cleanup, S-ready-for-review

#807 mam2/ntru: store full public key instead of public key id
  mam/v2/mam/mam.c
  mam/v2/mam/tests/test_mam.c
  mam/v2/ntru/ntru.c
  mam/v2/ntru/ntru.h
  mam/v2/ntru/ntru_types.c
  mam/v2/ntru/ntru_types.h
  mam/v2/ntru/tests/test_ntru.c
  mam/v2/ntru/tests/test_ntru_types.c
Labels: A-mam2, C-enhancement, S-ready-for-review

#814 mam2/mam: reduce scope of state variables
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
Labels: A-mam2, C-cleanup

#815 utils: support XTENSA toolchain.
  utils/handles/rand.h
  utils/handles/rw_lock.h
  utils/time.c
Labels: A-utils

#816 mam2/channel: add a msg ord field
  mam/v2/mam/channel.c
  mam/v2/mam/channel.h
  mam/v2/mam/tests/test_channel.c
Labels: A-mam2, C-enhancement

#810 mobile: android bindings implementation for trinity
  cclient/request/get_transactions_to_approve.c
  ciri/conf.c
  common/curl-p/pearl_diver.c
  common/errors.h
  common/helpers/checksum.c
  common/helpers/digest.c
  common/helpers/pow.c
  common/helpers/sign.c
  common/helpers/sign.h
  common/helpers/tests/test_sign.cpp
  common/model/transfer.c
  common/storage/sql/sqlite3/storage.c
  common/storage/sql/sqlite3/tests/test_sqlite3.c
  common/storage/sql/statements.c
  common/trinary/trit_array.c
  gossip/components/processor.c
  gossip/iota_packet.c
  gossip/neighbor.c
  gossip/transaction_request.c
  mam/v1/tests/test_mam.c
  mobile/android/BUILD
  mobile/android/Interface.cpp
  mobile/android/Interface.h
  mobile/android/demo/DummyActivity.java
  mobile/android/java/Interface.java
  utils/containers/hash/hash_queue.c.tpl
  utils/containers/hash/hash_set.c.tpl
  utils/containers/hash/hash_stack.c.tpl
  utils/containers/lock_free/lf_queue.c.tpl
  utils/containers/set.c.tpl
  utils/signed_files.c
Labels: A-mobile, C-feature-accepted

#817 mam2: pending sending state
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
  mam/v2/mam/tests/test_mam.c
Labels: A-mam2, C-cleanup

#822 mam2: remove unused code and move functions
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
  mam/v2/mam/mam_types.c
  mam/v2/mam/mam_types.h
  mam/v2/ntru/ntru.c
  mam/v2/ntru/ntru.h
Labels: A-mam2, C-cleanup

#823 common: fixing compile errors in ESP32.
  common/kerl/kerl.h
  utils/handles/socket.c
Labels: A-utils, C-enhancement

#819 mam2: bundle write header
  cclient/iota_client_extended_api.c
  common/errors.h
  common/model/transaction.c
  mam/v2/api/BUILD
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/examples/BUILD
  mam/v2/examples/send.c
  mam/v2/mam/channel.c
  mam/v2/mam/channel.h
  mam/v2/mam/mam.c
  mam/v2/mam/mam.h
  mam/v2/mam/tests/test_mam.c
Labels: A-mam2, C-feature-accepted

#824 mam2: clean message component
  mam/v2/api/BUILD
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/mam/BUILD
  mam/v2/mam/channel.c
  mam/v2/mam/channel.h
  mam/v2/mam/mam.h
  mam/v2/mam/message.c
  mam/v2/mam/message.h
  mam/v2/mam/tests/BUILD
  mam/v2/mam/tests/test_channel.c
  mam/v2/mam/tests/test_message.c
Labels: A-mam2, C-cleanup

#825 utils: add key_size to map and improve generator
  utils/containers/BUILD
  utils/containers/map.c.tpl
  utils/containers/map.h.tpl
  utils/containers/map_generator.bzl
  utils/containers/tests/test_map.c
Labels: A-utils, C-enhancement

#826 common: fix MSVC related errors
  common/model/bundle.c
  utils/time.c
Labels: A-common, C-bug

#829 mam2/api: save send contexts
  mam/v2/api/BUILD
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/examples/send.c
  mam/v2/mam/message.c
  mam/v2/mam/message.h
  mam/v2/mam/tests/test_message.c
  utils/containers/map.c.tpl
  utils/containers/map.h.tpl
  utils/containers/map_generator.bzl
  utils/containers/tests/test_map.c
Labels: A-mam2

#540 cclient/extended_api: iota_client_get_bundle and iota_client_traverse_bundle
  cclient/iota_client_extended_api.c
  cclient/iota_client_extended_api.h
  cclient/request/attach_to_tangle.c
  cclient/request/get_trytes.h
  cclient/serialization/tests/test_json.c
  common/error_strings.h
  common/errors.c
  common/errors.h
  common/model/transaction.c
  utils/containers/hash/hash_stack.c.tpl
  utils/containers/hash/hash_stack.h.tpl
  utils/containers/hash/tests/test_hash_stack.c
Labels: A-cclient, S-ready-for-review

#831 common/helpers: fix pow bundle
  common/helpers/pow.c
Labels: A-common, C-bug

#832 mam2/api: send packet
  common/errors.h
  common/model/bundle.c
  common/model/bundle.h
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/examples/send.c
Labels: A-mam2, C-feature-accepted

#834 mam2: merge recv contexts
  common/model/bundle.h
  mam/v2/api/api.c
  mam/v2/mam/message.c
  mam/v2/mam/message.h
  mam/v2/mam/tests/test_message.c
Labels: A-mam2, C-cleanup

#844 mam2: improved examples and use trytes for payload
  common/trinary/tests/test_tryte_ascii.c
  common/trinary/tryte_ascii.c
  common/trinary/tryte_ascii.h
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/examples/BUILD
  mam/v2/examples/common.h
  mam/v2/examples/recv.c
  mam/v2/examples/send.c
Labels: A-mam2, C-enhancement

#845 cclient: implementing iota_client_promote_transaction.
  cclient/iota_client_extended_api.c
  cclient/iota_client_extended_api.h
  cclient/request/attach_to_tangle.c
  cclient/request/attach_to_tangle.h
Labels: A-cclient

#848 cclient: fixing typo and memory leak issue.
  cclient/iota_client_extended_api.c
Labels: A-cclient

#847 mam2: extract PSK from mam folder and use PB3 encoding
  mam/v2/api/BUILD
  mam/v2/api/api.c
  mam/v2/api/api.h
  mam/v2/mam/BUILD
  mam/v2/mam/message.h
  mam/v2/mam/tests/BUILD
  mam/v2/ntru/BUILD
  mam/v2/ntru/ntru_types.c
  mam/v2/psk/BUILD
  mam/v2/psk/psk.c
  mam/v2/psk/psk.h
  mam/v2/psk/tests/BUILD
  mam/v2/psk/tests/test_psk.c
Labels: A-mam2, C-cleanup

#849 mam2: fix mam_seed conversion
  mam/v2/api/api.c
  mam/v2/examples/README.md
  mam/v2/examples/common.h
  mam/v2/examples/recv.c
  mam/v2/examples/send.c
Labels: A-mam2, C-enhancement

#863 mam2: api tests
  mam/v2/api/api.c
  mam/v2/api/tests/BUILD
  mam/v2/api/tests/test_api.c
  mam/v2/mam/tests/test_message.c
  mam/v2/mss/mss.c
  mam/v2/psk/psk.c
  mam/v2/trits/trits.c
Labels: A-mam2
